#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE DATABASE arcane WITH OWNER $POSTGRES_USER;
  CREATE DATABASE dockhand WITH OWNER $POSTGRES_USER;
  GRANT ALL PRIVILEGES ON DATABASE arcane TO $POSTGRES_USER;
  GRANT ALL PRIVILEGES ON DATABASE dockhand TO $POSTGRES_USER;
EOSQL
